apiVersion: v1
kind: Secret
metadata:
  name: showroom-pg-secret
  namespace: pc-showroom
type: Opaque
stringData:
  POSTGRES_USER: showroom
  POSTGRES_PASSWORD: showroom-db-2026
  POSTGRES_DB: showroom
  DATABASE_URL: "postgres://showroom:showroom-db-2026@showroom-pg:5432/showroom"
