apiVersion: v1
kind: PersistentVolume
metadata:
  name: showroom-pg-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my-local-storage
  claimRef:
    namespace: pc-showroom
    name: showroom-pg-claim
  local:
    path: /opt/k8s-pers/vol1/showroom-pg
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - mgplcb05
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: showroom-pg-claim
  namespace: pc-showroom
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-local-storage
  resources:
    requests:
      storage: 5Gi
  volumeName: showroom-pg-pv
